### ISSUE TITLE
endianity helper functions in util.h

### ISSUE THREAD

**Issue by pali** [fstirlitz/c-bsp#9] opened 2020-01-11 20:54 UTC
Hello!

This code
https://github.com/fstirlitz/c-bsp/blob/b15e82e08cb02bb1e88113664786c53c3c2e692c/src/lib/util.h#L35-L49
is suboptional when compiler does not have memcpy inlining optimizations. Function call is always slower as plain assignment. (Compiler may be smart and optimize-out functions from standard C library if library is bound with compiler).

IIRC gcc has in recent versions __builtint_memcpy which is used as replacement for memcpy calls when optimizations are enabled.

I compiled both variants with gcc 8.3 with enabled optimizations on x86 (32bit) and both produced same assembler output:

```asm
movl	4(%esp), %eax
movl	(%eax), %eax
```

So there is absolutely no need to have special code for big endian and special code for little endian.

Next, if you remove usage of `memcpy` function then following check
https://github.com/fstirlitz/c-bsp/blob/b15e82e08cb02bb1e88113664786c53c3c2e692c/src/lib/util.h#L17-L19
is useless.

`memcpy` is the only user of `char` type for which `CHAR_BIT` applies. C99 standard already says that `uint8_t` is always 8bit without padding, indepndently of how `char` type.

So theoretically C99 compiler may define that `char` is 7bit, but when `uint8_t` is provided it is always 8bit. But I do not know any C99 compiler which has char non-8-bit.

And last thing defining `get_le8` does not make sense as endianity is defined on bytes (not bits). So independently which endianity is used, one byte word would be always same. As for ordering of one byte (item) there is only option. It is just confusing in byte ordering endianity.

**Comment by aaaaaa123456789** [comment] 2020-01-11 21:01
A C99 compiler can't define `char` as 7 bits because 8 is the minimum. If a `uint8_t` type exists at all (which POSIX guarantees), then `char` must be 8 bits exactly.

That being said, GCC always optimizes `memcpy`, so there's no point in using GCC intrinsics instead of just `memcpy`.

Finally, the use of the stack for a function argument in your assembly output is strange... what calling convention is that?

**Comment by pali** [comment] 2020-01-11 21:10
> A C99 compiler can't define `char` as 7 bits because 8 is the minimum.

You are right. So just take any other value as a example.

> If a uint8_t type exists at all (which POSIX guarantees), then char must be 8 bits exactly.

I think that POSIX specify directly that it must be 8bits.

But above code does not require POSIX, it would work also without POSIX on any C99 compiler which defines those used `uintX_t` types.

In any case, on POSIX that check for `CHAR_BIT` is not needed at all and then `memcpy` is removed then also that check is not needed even for non-POSIX systems.

> Finally, the use of the stack for a function argument in your assembly output is strange... what calling convention is that?

I compiled that function as non-inline and dumped its assembler output. Just for simplicity. If compiler can optimize non-inline function it should also optimize its inline variant.

**Comment by fstirlitz** [comment] 2020-01-11 22:29
> Function call is always slower as plain assignment. (Compiler may be smart and optimize-out functions from standard C library if library is bound with compiler).
>
> IIRC gcc has in recent versions __builtint_memcpy which is used as replacement for memcpy calls when optimizations are enabled.

I wrote the code under the assumption that a compiler that defines `__BYTE_ORDER__` will have those optimisations. But even if it doesn't, the code will still compile and perform as intended, regardless of whether the compiler also provides `__builtin_memcpy` (unless `__BYTE_ORDER__` is lying, of course). If it performs suboptimally, incurs function call overhead, so be it; it's not that huge a cost anyway (and performance is not *that* big a deal for this project; I just wanted it leaner than [the JavaScript version](https://github.com/aaaaaa123456789/bsp/blob/master/bsppatch.js), and that's a pretty low bar to clear). I'm more worried about it performing incorrectly or not compiling at all.

> I compiled both variants with gcc 8.3 with enabled optimizations on x86 (32bit) and both produced same assembler output:

I remember using an earlier version of GCC which optimised `memcpy` calls, but not direct hand-written memory copy (It may or may not have depended on `-O` options). I'm glad to hear it's fixed now. Still, the code is not wrong and is unlikely to ever need changing, so I might as well keep it as-is.

> ```c
> #if CHAR_BIT != 8
> ```

Well, C99 mandates that `CHAR_BIT` ≥ 8, and if the `uint8_t` type exists (which I use) then it follows that `CHAR_BIT` ≤ 8 as well (because otherwise it's impossible to define a non-bitfield exactly 8 bits wide); not to mention POSIX directly mandating that `CHAR_BIT` simply equal 8. So this check may be a bit silly indeed. But these particular helpers could have been written in a way that depends on it less (for example, I could have used `uint_leastN_t` types), and I think it's nice to have an explicit reminder that as written here, they very much do depend on bytes being 8-bit.

> And last thing defining `get_le8` does not make sense as endianity is defined on bytes (not bits). So independently which endianity is used, one byte word would be always same. As for ordering of one byte (item) there is only option. It is just confusing in byte ordering endianity.

Fine, endianness of 1-byte values is a degenerate case. But I still need this helper defined for my poor man's generics: for example when [dispatching `get{byte,{half,}word}{,inc,dec}` opcodes](https://github.com/fstirlitz/c-bsp/blob/b15e82e08cb02bb1e88113664786c53c3c2e692c/src/lib/ops.c#L396-L419) or [fetching operands](https://github.com/fstirlitz/c-bsp/blob/b15e82e08cb02bb1e88113664786c53c3c2e692c/src/lib/ps.c#L44-L53).

> That being said, GCC always optimizes memcpy, so there's no point in using GCC intrinsics instead of just memcpy.

(The optimisation is disabled when `-fno-builtin-memcpy` is used;  `__builtin_memcpy` is not affected by that option. But as I said, I put correctness and portability first anyway.)

All in all, I don't think anything needs to be changed here (unless I change my mind on the `CHAR_BIT` issue), so closing. Feel free to point other things out, though.

**Closed by fstirlitz** 2020-01-11 22:29 UTC
Labels: wontfix, internals

**Comment by pali** [comment] 2020-01-11 22:57
> I remember using an earlier version of GCC which optimised `memcpy` calls, but not direct hand-written memory copy

If these ifdefs are just optimizations for earlier gcc version then it is OK. Maybe adding comment could help for new readers unaware of this fact what old versions of gcc can optimize and what not. (I have not did analysis of older gcc version, so I do not know that there was such bug).

> Still, the code is not wrong and is unlikely to ever need changing, so I might as well keep it as-is.

I agree that code is correct. It is up to you if you want / need to maintain 3 versions of same implementation for different versions of gcc compiler.

> Well, C99 mandates that `CHAR_BIT` ≥ 8, and if the `uint8_t` type exists (which I use) then it follows that `CHAR_BIT` ≤ 8 as well (because otherwise it's impossible to define a non-bitfield exactly 8 bits wide);

That is interesting conclusion, but make sense. Existance of `uint8_t` must imply that `CHAR_BIT` is 8.

> Fine, endianness of 1-byte values is a degenerate case. But I still need this helper defined for my poor man's generics:

Ok.

> That being said, GCC always optimizes `memcpy`, so there's no point in using GCC intrinsics instead of just `memcpy`.

I have not said that you should use gcc intrinsics. I said that gcc itself replaces `memcpy` to `__builtin_memcpy` when optimization are enabled. So gcc can fully optimize this function call.
